import Head from 'next/head'
import Image from 'next/image'
import Header from "@/components/Header";
import Modal from "@/components/Modal";
import {useState} from "react";
import SliderSection from "@/components/SliderSection";
import CalculatorSection from "@/components/CalculatorSection";
import CallbackForm from "@/components/CallbackForm";

export default function Home() {
    const [isClicked, setIsClicked] = useState(false);
    const [isCallbackClicked, setIsCallbackClicked] = useState(false);

    return (
    <>
      <Head>
        <title>Oxem</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header handleClick={setIsClicked} handleCallbackClick={setIsCallbackClicked}/>
      <Modal isClicked={isClicked} handleClick={setIsClicked} handleCallbackClick={setIsCallbackClicked}/>
      <SliderSection handleCallbackClick={setIsCallbackClicked}/>
      <CalculatorSection handleCallbackClick={setIsCallbackClicked}/>
      <CallbackForm isClicked={isCallbackClicked} handleCallbackClick={setIsCallbackClicked}/>
    </>
  )
}
